# Interface e Driver
interface=wlan0
driver=nl80211

# Configuração Básica Wi-Fi
ssid=TestSAE
hw_mode=g
channel=1
auth_algs=1

# Configuração WPA3-SAE
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
ieee80211w=2
sae_require_mfp=1

# Senha (tem de ser igual no cliente)
wpa_passphrase=password123



