interface=wlan0
driver=nl80211
ssid=TestEAP-PWD
hw_mode=g
channel=1

# --- ESTAS LINHAS SÃO OBRIGATÓRIAS PARA ENTERPRISE ---
ieee8021x=1          # ATIVA O MOTOR 802.1X/EAP
auth_algs=1          # OPEN SYSTEM AUTHENTICATION
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
ieee80211w=2
# ----------------------------------------------------

eap_server=1
eap_user_file=hostapd.eap_user
