# Configuração global
ctrl_interface=/var/run/wpa_supplicant
update_config=1

# Rede WPA3-Enterprise (EAP-pwd)
network={
    ssid="TestEAP-PWD"          # Tem de ser igual ao SSID no hostapd_enterprise.conf
    key_mgmt=WPA-EAP            # Importante: muda de SAE para WPA-EAP
    eap=PWD                     # Define o método EAP-password
    identity="teste"            # Tem de ser igual ao que puseste no hostapd.eap_user
    password="password123"      # A password que vai passar pelo PBKDF2
    ieee80211w=2                # MFP (Management Frame Protection) obrigatório no WPA3
}
