# Configuração global
ctrl_interface=/var/run/wpa_supplicant
update_config=1

# É AQUI que definimos que queremos apenas o Grupo 19
sae_groups=19

# Rede WPA3-SAE
network={
    ssid="TestSAE"
    key_mgmt=SAE
    proto=RSN
    ieee80211w=2
    sae_password="password123"
}
